---
title: "Exploratory"
output: github_document
date: "2025-10-07"
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

Import the weather data 

```{r}
data("weather_df")

weather_df = 
  weather_df |>
  mutate(
    month = lubridate::floor_date(date, unit = "month")) #rounding down the months ; essentially creating categorical variable 
```

Make plots 

```{r}
weather_df %>% 
  ggplot(aes(x=prcp))+
  geom_histogram()
```

Check on extreme values 
```{r}
weather_df %>% 
  filter(prcp>1000)
```

Look at the data again 
```{r}
weather_df %>% 
  filter(tmax>=20, tmax<=30) %>% 
  ggplot(aes(x=tmin,y=tmax,color=name,shape=name))+
  geom_point()
```

## Add groups 

```{r}
weather_df %>% 
  group_by(name,month) #gives us 72 combinations of name, month 
```

Group and count things 

```{r}
weather_df %>% 
  group_by(name) %>% 
  summarize(
    n=n() #shows us how many observations are in each name (central park, molokai, waterhole)
  )
```

```{r}
weather_df %>% 
  group_by(name,month) %>% 
  summarize(
    n=n_distinct(date)
  )
```

You can count directly 

```{r}
weather_df %>% 
  count(name) #short hand for saying group by name and count the observations under these 
```

## More interesting summaries 

Compute some extra stuff 
```{r}
weather_df %>% 
  group_by(name,month) %>% 
  summarize(
    mean_tmax=mean(tmax, na.rm=TRUE), #computing average temperatures for each month since that's what we grouped by; if observation is missing then you get an NA 
    median_tmin=median(tmin,na.rm=TRUE),
    sd_prcp=sd(prcp,na.rm=TRUE)
  )
```

This is still a data frame 
```{r}
weather_df %>% 
  group_by(name,month) %>% #each possible combination of the name variable and month variable will define a distinct group 
  summarize(
    mean_tmax=mean(tmax,na.rm=TRUE)
  ) %>% 
  pivot_wider(
    names_from=name,
    values_from=mean_tmax
  ) %>% 
  knitr::kable(digits=2)
```

## mutate with groups 

```{r}
weather_df %>% 
  group_by(name) %>% #the mean that will display will be based on the central park, waterhole, molokai 
  mutate(
    mean_tmax=mean(tmax,na.rm=TRUE),
    center_tmax=tmax-mean_tmax
  ) %>% 
  ggplot(aes(x=date,y=center_tmax,color=name))+
  geom_point()
```

Look for cold days 
```{r}
weather_df %>% 
  group_by(name,month) %>% 
  mutate(temp_rank=min_rank(desc(tmin))) %>%  #ranks coldest days 
  filter(temp_rank<2)
```

What about lags ? 

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(lagged_tmax=lag(tmax))
```

Use the variables you create 
```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    temp_change=tmax-lag(tmax)
  ) %>% 
  summarize(
    sd_tmax_change=sd(temp_change,na.rm=TRUE),
    tmax_change_max=max(temp_change,na.rm=TRUE)
  )
```

## Revisit pulse 
```{r}
pulse_df=
  haven::read_sas("datasets/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to="visit",
    names_prefix="bdi_score_", #gets rid of prefix so axis is cleaner 
    values_to="bdi"
  ) %>% 
  mutate(visit=fct_inorder(visit)) #this solves the problem below

pulse_df %>% 
  ggplot(aes(x=visit,y=bdi))+
  geom_boxplot() #issue with this initial plot is that BL comes last due to alphabetical 

pulse_df %>% 
  group_by(visit) %>% 
  summarise(
    median_bdi=median(bdi,na.rm=TRUE),
    mean_bdi=mean(bdi,na.rm=TRUE)
  ) %>% 
  knitr::kable(digits=2)
```




